### ISSUE TITLE
访问本仓库 TechStack 时，显示“没有找到该仓库的技术栈”

### ISSUE THREAD

**Issue by coolmian** [Get-Tech-Stack/TechStack#1]
chrome 拓展 版本1.6

**Comment by CorrectRoadH** [comment]
👀这个问题是由于后端缓存导致的。

因为本仓库之前是只有README的，然后一个群友建议我把 TechStack 给开源，因为 TechStack 是浏览器插件，会涉及很多权限。如果开源的话可以确保不作恶。所以今天才开源的。

然后之前本仓库的缓存还没有失效，所以显示的是之前的没有找到技术栈。

**Comment by coolmian** [comment]
现在已经能看到了
