### ISSUE TITLE
The Chrome Extension not working

### ISSUE THREAD

**Issue by einverne** [Get-Tech-Stack/TechStack#13]
When I installed the Chrome Extension, I see

<img width="316" alt="image" src="https://github.com/Get-Tech-Stack/TechStack/assets/1962738/8658757f-d434-4b5c-b727-4b705d000658">

Then I checked the following api request

<img width="753" alt="image" src="https://github.com/Get-Tech-Stack/TechStack/assets/1962738/c0284a21-f7db-4669-ad15-169a17682154">

it shows:
<img width="744" alt="image" src="https://github.com/Get-Tech-Stack/TechStack/assets/1962738/fef5e4e0-c5a4-4b3e-8313-1d8b837269b5">

Looks like Zeabur is not stable.

**Comment by CorrectRoadH** [comment]
Sorry for that. This has now been fixed. Because zeabur is somewhat unstable, one service crashes causing multiple service errors.🥺

**Comment by einverne** [comment]
Anyway, thank you for providing such a great tool.
