### ISSUE TITLE
Failed to show Tech Stack

### ISSUE THREAD

**Issue by YuliangXiaoYLX** [Get-Tech-Stack/TechStack#17]
Hi, thanks for your great work. Currently I faced an issue that the Tech Stack cannot show the GitHub Tech Stack information on Chrome (```Version 130.0.6723.59 (Official Build) (arm64)```). Could anyone help me solve it? The screenshot of bug is attached, thanks in advance!

![Screenshot 2024-10-16 at 13 28 42](https://github.com/user-attachments/assets/12c47620-2ec2-48ea-bcd2-0b64080f4306)

**Comment by CorrectRoadH** [comment]
Thanks for your feedback, it has been fixed
