### ISSUE TITLE
关于插件Logo

### ISSUE THREAD

**Issue by AzumWatson** [Get-Tech-Stack/TechStack#3]
![image](https://github.com/Get-Tech-Stack/TechStack/assets/102755150/3b27075a-3a7b-4af9-aa91-2daf27026fc0)

建议把四角的白色部分换成透明，不然在不同配色下就有点不好看

**Comment by CorrectRoadH** [comment]
🤔是一个好建议，在下个版本(1.17)，我将会修改图标
