### ISSUE TITLE
修改或允许用户修改TechStack显示位置

### ISSUE THREAD

**Issue by du33169** [Get-Tech-Stack/TechStack#4]
现在默认显示在右侧最上方，甚至比项目的About还高，我认为不大合适，建议可以和Languages放在一起

**Comment by CorrectRoadH** [comment]
目前新版本已经提供当技术栈过多时自动折叠功能: https://twitter.com/GetTechStack/status/1701565062258000279 
和修改显示位置功能: https://twitter.com/GetTechStack/status/1701568475972710838

应该能满足您的需求🎉
