### ISSUE TITLE
获取不存在的仓库时后端会崩溃

### ISSUE THREAD

**Issue by AnotiaWang** [Get-Tech-Stack/TechStack#5]
示例：发请求给 https://techstack.zeabur.app/repo?url=https://github.com/nuxt/nuxt1

就会返回 Zeabur 的“App Crashed”页面

**Comment by CorrectRoadH** [comment]
好的，感谢你的反馈。我马上修复一下👌

**Comment by AnotiaWang** [comment]
请问后端有没有开源的计划呢

**Comment by CorrectRoadH** [comment]
> 请问后端有没有开源的计划呢

目前是没有开源的计划。

后端不开源的原因主要有两个: 一个是代码比较乱，一个没有self host的价值。 

前者问题正在解决中，最近也会经常写博客分享遇到的各种技术问题和解决思路，一般可以满足想通过看代码来学习的人。

后者是没必要开源的回答。比如自己搭建后端的话也不会说用起来体验更好。  其次后端部署起来涉及的组件多，缺少一些自动部署的脚本和文档，我补齐会需要一定的时间
