### ISSUE TITLE
与 refined-github 插件冲突，插入内容不显示

### ISSUE THREAD

**Issue by Ares-Chang** [Get-Tech-Stack/TechStack#6]
您好，插件非常棒，如果可以保持准确性的话，可以有效避免开启 package.json 的情况😁。

我有一个建议，这是我安装插件后显示的内容。

![image](https://github.com/Get-Tech-Stack/TechStack/assets/36911513/bed01b4d-e6bd-4916-8540-76b101207c2f)

它的插入位置处于信息栏的最上方，是否应该把它插入到底部或者特定位置呢？如，这里：

![image](https://github.com/Get-Tech-Stack/TechStack/assets/36911513/fd1e0ee4-d0aa-419b-bbef-9ca719474470)

因为个人感觉，仓库的简介信息会比较重要一点，而且如果仓库使用的技术内容少一点，显示的布局可能可以优化一下。

希望优化插入位置，但不影响这是个非常棒的 Idea!

**Comment by CorrectRoadH** [comment]
感谢您的反馈🙏

如果技术栈太多的话，现在已经可以自动折叠了。
https://github.com/Get-Tech-Stack/TechStack/assets/29306285/ac879035-7238-4b8f-a74c-b8fe2000303b

然后修改插件出现的位置的功能已经支持了，可以在选项页面中改，视频教程如下👇
https://twitter.com/GetTechStack/status/1701568475972710838

不过暂时是无法放到最下面。不过应该已经能满足你的需求。

**Comment by CorrectRoadH** [comment]
🤣准确性是可以保证的。如果不能保证，那么就是一个BUG。遇到的话，可以反馈给我。我马上修。

**Comment by Ares-Chang** [comment]
谢谢，我一开始点击插件图标跳转了 GitHub 页，我以为没有设置功能。😂

但是这个插件和像和 [refined-github](https://github.com/refined-github/refined-github) 的插件冲突了，设置后并没有在指定位置显示。

![image](https://github.com/Get-Tech-Stack/TechStack/assets/36911513/651657cd-81c3-4c1f-ad0f-d887f0abcbfd)

而且，你截图中我看显示的都是英文的标题，这个应该怎么设置呢？

**Comment by CorrectRoadH** [comment]
> 谢谢，我一开始点击插件图标跳转了 GitHub 页，我以为没有设置功能。😂
> 
> 但是这个插件和像和 [refined-github](https://github.com/refined-github/refined-github) 的插件冲突了，设置后并没有在指定位置显示。
> 
> ![image](https://user-images.githubusercontent.com/36911513/271150096-651657cd-81c3-4c1f-ad0f-d887f0abcbfd.png)
> 
> 而且，你截图中我看显示的都是英文的标题，这个应该怎么设置呢？

好的，估计是refined-Github改成类名，我晚些时候看看能不能兼容一下。👌 关于标题是和i18n相关，具体是跟随浏览器的语言还是ip这个就不太清楚具体的判断方式了。

**Comment by CorrectRoadH** [comment]
> 谢谢，我一开始点击插件图标跳转了 GitHub 页，我以为没有设置功能。😂
> 
> 但是这个插件和像和 [refined-github](https://github.com/refined-github/refined-github) 的插件冲突了，设置后并没有在指定位置显示。
> 
> ![image](https://user-images.githubusercontent.com/36911513/271150096-651657cd-81c3-4c1f-ad0f-d887f0abcbfd.png)
> 
> 而且，你截图中我看显示的都是英文的标题，这个应该怎么设置呢？

你是不是还装了其它插件或者美化工具，我刚刚试了一下和 refined-github 一起用是没有问题的。

**Comment by Ares-Chang** [comment]
sorry, 我尝试关了别的插件，但是无法完全复现出现。我用两个项目页面刷新，这个模块时有时无的，我无法完全定位问题。

非常感谢，如果我能完全定位问题后，再来开启 issues😅

**Comment by CorrectRoadH** [comment]
> sorry, 我尝试关了别的插件，但是无法完全复现出现。我用两个项目页面刷新，这个模块时有时无的，我无法完全定位问题。
> 
> 非常感谢，如果我能完全定位问题后，再来开启 issues😅

🤣这样bug看起来更可怕了
